// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef CubeViewUI_h
#define CubeViewUI_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Value_Output.H>
#include<iostream>
using namespace std;
#include "CubeView.h"

class CubeViewUI {
public:
  CubeViewUI();
  Fl_Window *mainWindow;
  Fl_Group *VChange;
  Fl_Roller *vrot;
private:
  inline void cb_vrot_i(Fl_Roller*, void*);
  static void cb_vrot(Fl_Roller*, void*);
public:
  Fl_Value_Slider *ypan;
private:
  inline void cb_ypan_i(Fl_Value_Slider*, void*);
  static void cb_ypan(Fl_Value_Slider*, void*);
public:
  Fl_Value_Output *v_val;
  Fl_Group *HChange;
  Fl_Roller *hrot;
private:
  inline void cb_hrot_i(Fl_Roller*, void*);
  static void cb_hrot(Fl_Roller*, void*);
public:
  Fl_Value_Slider *xpan;
private:
  inline void cb_xpan_i(Fl_Value_Slider*, void*);
  static void cb_xpan(Fl_Value_Slider*, void*);
public:
  Fl_Value_Output *h_val;
  Fl_Group *MainView;
  CubeView *cube;
  Fl_Value_Slider *zoom;
private:
  inline void cb_zoom_i(Fl_Value_Slider*, void*);
  static void cb_zoom(Fl_Value_Slider*, void*);
public:
  void show(int argc, char** argv);
};
#endif
