// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef use_chinese_h
#define use_chinese_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>

class Hello {
public:
  Hello();
  Fl_Double_Window *win;
  Fl_Text_Display *text;
  void show(int argc, char**argv);
};
#endif
