// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef show_gif_h
#define show_gif_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>

class Hello {
public:
  Hello();
  Fl_Double_Window *win;
  Fl_Box *frame;
  void show(int argc, char**argv);
};
#endif
