// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "show_gif.h"

Hello::Hello() {
  { win = new Fl_Double_Window(322, 291, "\344\275\240\345\245\275\344\270\226\347\225\214");
    win->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 1, 320, 284);
      { frame = new Fl_Box(5, 5, 315, 280);
        frame->labeltype(FL_NO_LABEL);
      } // Fl_Box* frame
      o->end();
    } // Fl_Group* o
    win->end();
  } // Fl_Double_Window* win
}

void Hello::show(int argc, char**argv) {
  win->show(argc, argv);
}
